
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Center_Application.DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbEmployee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbEmployee()
    {

        this.tbCourses = new HashSet<tbCours>();

    }


    public int ID { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Notes { get; set; }

    public string Occuption { get; set; }

    public Nullable<decimal> Salary { get; set; }

    public string Image { get; set; }

    public string employeeName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbCours> tbCourses { get; set; }

}

}
