

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Center_Application.DB
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbCoursesCenterEntities : DbContext
{
    public dbCoursesCenterEntities()
        : base("name=dbCoursesCenterEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbCategory> tbCategories { get; set; }

    public virtual DbSet<tbCours> tbCourses { get; set; }

    public virtual DbSet<tbEmployee> tbEmployees { get; set; }

    public virtual DbSet<tbStudent> tbStudents { get; set; }

    public virtual DbSet<tbUser> tbUsers { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<StudentsDetail> StudentsDetails { get; set; }

}

}

