
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Center_Application.DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbCours
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbCours()
    {

        this.StudentsDetails = new HashSet<StudentsDetail>();

    }


    public int ID { get; set; }

    public Nullable<decimal> Price { get; set; }

    public string Instructor { get; set; }

    public string Notes { get; set; }

    public string Image { get; set; }

    public Nullable<int> Categoryid { get; set; }

    public Nullable<int> Employeesid { get; set; }

    public Nullable<int> Usersid { get; set; }

    public string courseName { get; set; }



    public virtual tbCategory tbCategory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentsDetail> StudentsDetails { get; set; }

    public virtual tbEmployee tbEmployee { get; set; }

    public virtual tbUser tbUser { get; set; }

}

}
